import requests
import json
import time
from collections import defaultdict

# 1. Definiere die Orte, deren Koordinaten gefunden werden müssen
CITY_NAMES = [
    "Tokyo",
"Delhi",
"Shanghai",
"Sao Paulo",
"Mexico City",
"Dhaka",
"Cairo",
"Beijing",
"Mumbai",
"Osaka",
"Karachi",
"Chongqing",
"Istanbul",
"Kinshasa",
"Lagos",
"Buenos Aires",
"Kolkata",
"Manila",
"Tianjin",
"Los Angeles",
"Moscow",
"Shenzhen",
"Jakarta",
"Lahore",
"Bangalore",
"Paris",
"Seoul",
"Lima",
"Chicago",
"London",
"Tehran",
"Bogota",
"Chennai",
"Guangzhou",
"Wenzhou",
"Nanjing",
"Wuhan",
"Hyderabad",
"Nagoya",
"Miami",
"Boston",
"Johannesburg",
"Bangkok",
"Riyadh",
"Hong Kong",
"Hanoi",
"Ho Chi Minh City",
"Zhengzhou",
"Qingdao",
"Kuala Lumpur",
"Santiago",
"Dallas",
"Philadelphia",
"Barcelona",
"Singapore",
"Baghdad",
"Houston",
"Toronto",
"St. Petersburg",
"Belo Horizonte",
"San Francisco",
"Madrid",
"Xian",
"Hangzhou",
"Sūrat",
"Detroit",
"Khartoum",
"Ahmedabad",
"Abidjan",
"Yangon",
"Sydney",
"Mogadishu",
"Harbin",
"Algiers",
"San Juan",
"Dar es Salaam",
"Pune",
"Alexandria",
"Milan",
"Tel Aviv",
"Lisbon",
"Taipei",
"New York",
"Dubai",
"Washington D.C.",
"Auckland",
"Berlin",
"Fuzhou",
"Mecca",
"Kunming",
"Nairobi",
"Durban",
"Montreal", 
"Seattle",
"Minneapolis",
"Kyoto",
"Rome",
"Recife",
"Guayaquil",
"Dalian",
"Suzhou",
"Jinan",
"Changsha",
"Luoyang",
"Addis Ababa",
"Incheon",
"Tampa",
"Phoenix",
"Guadalajara",
"Bandung",
" ",
"Mashhad",
"Izmir",
"Porto Alegre",
"Vancouver",
"San Diego",
"Dammam",
"Busan",
"Kano",
"Fortaleza",
"Salvador",
"Puebla",
"San Antonio",
"Accra",
"Medan",
"Rotterdam",
"Casablanca",
"Sapporo",
"Osaka",
"Lille",
"Marseille",
"Hamburg",
"Munich",
"Vienna",
"Brussels",
"Warsaw",
"Stockholm",
"Copenhagen",
"Oslo",
"Dublin",
"Manchester",
"Birmingham",
"Glasgow",
"Frankfurt",
"Zurich",
"Geneva",
"Prague",
"Budapest",
"Bucharest",
"Athens",
"Helsinki",
"Amman",
"Doha",
"Abu Dhabi",
"Kuwait City",
"Manama",
"Beirut",
"Damascus",
"Jeddah",
"Luanda",
"Medellín",
"Hefei",
"Shaoxing",
"Datong",
"Indore",
"Faisalabad",
"Kobe",
"Sendai",
"Taiyuan",
"Chiba",
"Okayama",
"Minsk",
"Dnipro",
"Odesa",
"Tijuana",
"Monterrey",
"Fez",
"Marrakech",
"Dakar",
"Abuja",
"Omdurman",
"Brazzaville",
"Lubumbashi",
"Havana",
"Portland",
"San Jose",
"Sacramento",
"Denver",
"Mesa",
"Atlanta",
"Charlotte",
"Virginia Beach",
"Santo Domingo",
"Port-au-Prince",
"Kingston",
"Quito",
"Cali",
"Barranquilla",
"Caracas",
"Maracaibo",
"Guayaquil",
"Montevideo",
"Cordoba",
"Rosario",
"Curitiba",
"Recife",
"Belo Horizonte",
"Manaus",
"Brasília",
"Goiânia",
"Peshawar",
"Rawalpindi",
"Multan",
"Foshan",
"Dongguan",
"Zhongshan",
"Shantou",
"Xiamen",
"Nanchang",
"Haikou",
"Lhasa",
"Urumqi",
"Novosibirsk",
"Yekaterinburg",
"Nizhny Novgorod",
"Samara",
"Omsk",
"Kazan",
"Chelyabinsk",
"Rostov-on-Don",
"Ufa",
"Perm",
"Volgograd",
"Krasnoyarsk",
"Voronezh",
"Saratov",
"Tolyatti",
"Izhevsk",
"Khabarovsk",
"Vladivostok",
"Irkutsk",
"Barnaul",
"Manado",
"Semarang",
"Palembang",
"Makassar",
"Denpasar",
"Bandar Lampung",
"Patna",
"Jaipur",
"Kanpur",
"Lucknow",
"Nagpur",
"Coimbatore",
"Kochi",
"Gaziantep",
"Adana",
"Bursa",
"Antalya",
"Konya",
"Mersin",
"Samsun",
"Eskişehir",
"Erbil",
"Mosul",
"Basra",
"Kirkuk",
"Sana'a",
"Aden",
"Aleppo",
"Homs",
"Latakia",
"Tripoli (Lebanon)",
"Zarqa",
"Irbid",
"Ramallah",
"Gaza City",
"Hebron",
"Jaffa",
"Haifa",
"Jerusalem",
"Rabat",
"Tripoli (Libya)",
"Benghazi",
"Tunis",
"Oujda",
"Setif",
"Oran",
"Luanda",
"Maputo",
"Harare",
"Lusaka",
"Gaborone",
"Windhoek",
"Maseru",
"Banjul",
"Conakry",
"Freetown",
"Monrovia",
"Bamako",
"Niamey",
"Ouagadougou",
"Lomé",
"Cotonou",
"Yaoundé",
"Douala",
"Libreville",
"Malabo",
"N'Djamena",
"Khartoum North",
"Port Sudan",
"Juba",
"Bujumbura",
"Kigali",
"Kampala",
"Mwanza",
"Mombasa",
"Nampula",
"Beira",
"Antananarivo",
"Port Louis",
"Saint-Denis",
"Nouméa",
"Suva",
"Port Moresby",
"Honiara",
"Vila",
"Papeete",
"Honolulu",
"Anchorage",
"Las Vegas",
"Reno",
"Salt Lake City",
"Boise",
"Billings",
"Omaha",
"Kansas City",
"St. Louis",
"Milwaukee",
"Cincinnati",
"Cleveland",
"Columbus",
"Indianapolis",
"Louisville",
"Nashville",
"Memphis",
"New Orleans",
"Birmingham (US)",
"Jacksonville",
"Orlando",
"Charleston",
"Raleigh",
"Richmond",
"Norfolk",
"Buffalo",
"Rochester",
"Syracuse",
"Albany",
"Providence",
"Hartford",
"New Haven",
"Bridgeport",
"Jersey City",
"Newark",
"Paterson",
"Allentown",
"Harrisburg",
"Wilmington",
"Baltimore",
"Tulsa",
"Oklahoma City",
"Little Rock",
"Wichita",
"Albuquerque",
"El Paso",
"Tucson",
"Oakland",
"Fresno",
"Bakersfield",
"Long Beach",
"Anaheim",
"Santa Ana",
"Riverside",
"San Bernardino",
"Stockton",
"Modesto",
"Corpus Christi",
"Laredo",
"Austin",
"Fort Worth",
"Des Moines",
"Madison",
"Green Bay",
"Grand Rapids",
"Lansing",
"Toledo",
"Akron",
"Dayton",
"Lexington",
"Knoxville",
"Chattanooga",
"Huntsville",
"Mobile",
"Montgomery",
"Shreveport",
"Baton Rouge",
"Lafayette",
"Jackson",
"Columbia",
"Greenville",
"Greensboro",
"Winston-Salem",
"Durham",
"Fayetteville",
"Wilmington (NC)",
"Pensacola",
"Tallahassee",
"Hialeah",
"Fort Lauderdale",
"West Palm Beach",
"Cape Coral",
"Clearwater",
"Lakeland",
"Deltona",
"Daytona Beach",
"Gainesville",
"Port St. Lucie",
"Springfield (MA)",
"Worcester",
"Lowell",
"Cambridge",
"Manchester (NH)",
"Nashua",
"Burlington",
"Portland (ME)",
"New Bedford",
"Fall River",
"Peoria",
"Rockford",
"Joliet",
"Naperville",
"Aurora (IL)",
"South Bend",
"Fort Wayne",
"Gary",
"Evansville",
"Cedar Rapids",
"Davenport",
"Sioux Falls",
"Fargo",
"Bismarck",
"Rapid City",
"Cheyenne",
"Lubbock",
"Amarillo",
"Midland",
"Odessa",
"Abilene",
"Killeen",
"Waco",
"McAllen",
"Brownsville",
"San Angelo",
"Pasadena (TX)",
"Plano",
"Garland",
"Irving",
"Richardson",
"Frisco",
"Denton",
"Carrollton",
"Lewisville",
"Sugar Land",
"The Woodlands",
"Beaumont",
"Port Arthur",
"Galveston",
"Wichita Falls",
"Norman",
"Broken Arrow",
"Lawton",
"Fayetteville (AR)",
"Fort Smith",
"Jonesboro",
"Springfield (MO)",
"Independence (MO)",
"Columbia (MO)",
"Joplin",
"St. Joseph",
"Overland Park",
"Kansas City (KS)",
"Topeka",
"Olathe",
"Santa Fe",
"Roswell",
"Farmington",
"Las Cruces",
"Missoula",
"Great Falls",
"Butte",
"Pocatello",
"Idaho Falls",
"Carson City",
"Henderson",
"North Las Vegas",
"Sparks",
"Ogden",
"Provo",
"West Valley City",
"Orem",
"St. George",
"Greeley",
"Colorado Springs",
"Aurora (CO)",
"Fort Collins",
"Lakewood",
"Westminster",
"Arvada",
"Pueblo",
"Centennial",
"Thornton",
"Boulder",
"Renton",
"Tacoma",
"Bellevue",
"Everett",
"Spokane",
"Vancouver (WA)",
"Eugene",
"Salem",
"Gresham",
"Hillsboro",
"Beaverton",
"Medford",
"Springfield (OR)",
"Temecula",
"Escondido",
"Oceanside",
"Carlsbad",
"Vista",
"Indio",
"Lancaster",
"Palmdale",
"Torrance",
"Pomona",
"Downey",
"Glendale",
"Pasadena (CA)",
"El Monte",
"Inglewood",
"Compton",
"Norwalk",
"Burbank",
"Rialto",
"Fontana",
"Moreno Valley",
"Rancho Cucamonga",
"Ontario",
"Corona",
"Irvine",
"Huntington Beach",
"Garden Grove",
"Santa Clarita",
"Simi Valley",
"Thousand Oaks",
"Oxnard",
"Ventura",
"Santa Barbara",
"Santa Maria",
"San Luis Obispo",
"Salinas",
"Hayward",
"Fremont",
"Sunnyvale",
"Santa Clara",
"Concord",
"Vallejo",
"Fairfield",
"Richmond (CA)",
"Berkeley",
"Daly City",
"San Mateo",
"Redwood City",
"Mountain View",
"Palo Alto",
"Santa Rosa",
"Petaluma",
"Davis",
"Vacaville",
"Tracy",
"Merced",
"Turlock",
"Madera",
"Visalia",
"Tulare",
"Hanford",
"Lodi",
"Elk Grove",
"Roseville",
"Citrus Heights",
"Folsom",
"Yuba City",
"Redding",
"Chico",
"Eureka",
"San Rafael",
"Novato",
"Livermore",
"Pleasanton",
"Antioch",
"Pittsburg",
"Brentwood",
"Walnut Creek",
"Danville",
"San Ramon",
"Dublin",
"Pleasant Hill",
"Martinez",
"San Pablo",
"Hercules",
"Pinole",
"El Cerrito",
"Mill Valley",
"San Anselmo",
"Larkspur",
"Corte Madera",
"Tiburon",
"Sausalito",
"Belvedere",
"Piedmont",
"Albany (CA)",
"Emeryville",
"Brisbane",
"Millbrae",
"Burlingame",
"San Bruno",
"Foster City",
"Pacifica",
"Half Moon Bay",
"Saratoga",
"Los Gatos",
"Campbell",
"Cupertino",
"Milpitas",
"Morgan Hill",
"Gilroy",
"Scotts Valley",
"Capitola",
"Watsonville",
"Marina",
"Seaside",
"Monterey",
"Pacific Grove",
"Carmel-by-the-Sea",
"King City",
"Soledad",
"Gonzales",
"Greenfield",
"Hollister",
"Atascadero",
"Morro Bay",
"Paso Robles",
"Lompoc",
"Goleta",
"Carpinteria",
"Fillmore",
"Santa Paula",
"Port Hueneme",
"Camarillo",
"Moorpark",
"Westlake Village",
"Agoura Hills",
"Calabasas",
"Malibu",
"West Hollywood",
"Beverly Hills",
"Culver City",
"Santa Monica",
"Venice",
"Manhattan Beach",
"Hermosa Beach",
"Redondo Beach",
"Palos Verdes Estates",
"Rancho Palos Verdes",
"Rolling Hills Estates",
"Rolling Hills",
"Lakewood",
"Cerritos",
"Artesia",
"Bellflower",
"Paramount",
"Lynwood",
"South Gate",
"Huntington Park",
"Bell",
"Bell Gardens",
"Maywood",
"Cudahy",
"Commerce",
"Vernon",
"Montebello",
"Monterey Park",
"Alhambra",
"San Gabriel",
"Rosemead",
"Temple City",
"San Marino",
"South Pasadena",
"La Cañada Flintridge",
"Arcadia",
"Monrovia",
"Duarte",
"Azusa",
"Glendora",
"Covina",
"West Covina",
"Walnut",
"Diamond Bar",
"Claremont",
"La Verne",
"San Dimas",
"Chino",
"Upland",
"Montclair",
"La Habra",
"Brea",
"Fullerton",
"Yorba Linda",
"Placentia",
"Tustin",
"Orange",
"Villa Park",
"Laguna Beach",
"Newport Beach",
"Costa Mesa",
"Fountain Valley",
"Westminster",
"Stanton",
"Cypress",
"Los Alamitos",
"Seal Beach",
"La Palma",
"Buena Park",
"Lake Forest",
"Mission Viejo",
"Aliso Viejo",
"Laguna Niguel",
"Dana Point",
"San Clemente",
"San Juan Capistrano",
"Rancho Santa Margarita",
"Ladera Ranch",
"Coto de Caza",
"Trabuco Canyon",
"Silverado Canyon",
"Modjeska Canyon",
"Victorville",
"Hesperia",
"Adelanto",
"Barstow",
"Twentynine Palms",
"Yucca Valley",
"Needles",
"Blythe",
"El Centro",
"Brawley",
"Calexico",
"Holtville",
"Westmorland",
"Calipatria",
"Imperial",
"San Fernando",
"Big Bear Lake",
"Lake Arrowhead",
"Running Springs",
"Crestline",
"Wrightwood",
"Lytle Creek",
"Pinon Hills",
"Phelan",
"El Mirage",
"Pearblossom",
"Littlerock",
"Llano",
"Acton",
"Agua Dulce",
"Castaic",
"Newhall",
"Saugus",
"Valencia",
"Stevenson Ranch",
"Canyon Country",
"Fair Oaks",
"Carmichael",
"Arden-Arcade",
"Florin",
"Rancho Cordova",
"Galt",
"Isleton",
"Courtland",
"Walnut Grove",
"Lockeford",
"Acampo",
"Woodbridge",
"Thornton (CA)",
"Herald",
"Plymouth",
"Ione",
"Sutter Creek",
"Jackson",
"San Andreas",
"Angels Camp",
"Sonora",
"Jamestown",
"Columbia",
"Twain Harte",
"Groveland",
"Yosemite Valley",
"Mariposa",
"Oakhurst",
"Chowchilla",
"Mendota",
"Firebaugh",
"Kerman",
"Coalinga",
"Huron",
"Avenal",
"Corcoran",
"Lemoore",
"Exeter",
"Lindsay",
"Porterville",
"Strathmore",
"Dinuba",
"Reedley",
"Sanger",
"Clovis",
"El Dorado Hills",
"Cameron Park",
"Shingle Springs",
"Placerville",
"Pollock Pines",
"South Lake Tahoe",
"Truckee",
"Tahoe City",
"Tahoe Vista",
"Kings Beach",
"Incline Village",
"Zephyr Cove",
"Stateline",
"Minden",
"Gardnerville",
"Yerington",
"Hawthorne",
"Mina",
"Schurz",
"Walker Lake",
"Bishop",
"Mammoth Lakes",
"June Lake",
"Bridgeport",
"Coleville",
"Topaz",
"Lee Vining",
"June Lake",
"Mammoth Lakes",
"Independence (CA)",
"Lone Pine",
"Big Pine",
"Olancha",
"Cartago",
"Darwin",
"Tecopa",
"Shoshone",
"Trona",
"Boron",
"Mojave",
"Rosamond",
"California City",
"Tehachapi",
"Frazier Park",
"Taft",
"Wasco",
"Shafter",
"Delano",
"McFarland",
"Richgrove",
"Earlimart",
"Pixley",
"Tipton",
"Goshen",
"Farmersville",
"Woodlake",
"Lemon Cove",
"Three Rivers",
"Springville",
"California Hot Springs",
"Kernville",
"Lake Isabella",
"Oildale",
"Greenacres",
"Lamont",
"Arvin",
"Weedpatch",
"Mcnair",
"Ridgecrest",
"Inyokern",
"Arvin",
"Weedpatch",
"Mcnair",
"Ridgecrest",
"Inyokern",
"Lovelock",
"Winnemucca",
"Elko",
"Ely",
"Fallon",
"Fernley",
"Gardnerville Ranchos",
"Pahrump",
"Spanish Springs",
"Sun Valley",
"Washoe Valley",
"Zion Canyon",
"Moab",
"Cedar City",
"Hurricane",
"Kanab",
"Page (AZ)",
"Tuba City",
"Kayenta",
"Winslow",
"Flagstaff",
"Sedona",
"Prescott",
"Kingman",
"Bullhead City",
"Lake Havasu City",
"Yuma",
"Casa Grande",
"Maricopa",
"Eloy",
"Florence",
"Coolidge",
"Safford",
"Thatcher",
"Globe",
"Payson",
"Show Low",
"Lakeside",
"Pinetop-Lakeside",
"Holbrook",
"Snowflake",
"Springerville",
"Alpine",
"Clifton",
"Morenci",
"Willcox",
"Benson",
"Sierra Vista",
"Nogales",
"Douglas",
"Bisbee",
"Ajo",
"Gila Bend",
"Buckeye",
"Surprise",
"Peoria",
"Scottsdale",
"Tempe",
"Chandler",
"Gilbert",
"Queen Creek",
"Apache Junction",
"San Tan Valley",
"Marana",
"Oro Valley",
"Sahuarita",
"Green Valley",
"Vail"
    # ... hier tausende weitere Städtenamen einfügen
]

def get_coordinates(city_name):
    """
    Ruft Breitengrad und Längengrad für einen Stadtnamen über die Open-Meteo Geocoding API ab.
    """
    GEOCODING_URL = "https://geocoding-api.open-meteo.com/v1/search"
    params = {
        "name": city_name,
        "count": 1,  # Nur das relevanteste Ergebnis
        "language": "de",
        "format": "json"
    }
    
    try:
        response = requests.get(GEOCODING_URL, params=params)
        response.raise_for_status()
        data = response.json()
        
        if data.get('results'):
            result = data['results'][0]
            return {
                "name": result.get('name', city_name),
                "lat": result['latitude'],
                "lng": result['longitude']
            }
        else:
            print(f"Warnung: Keine Koordinaten für '{city_name}' gefunden.")
            return None
            
    except requests.exceptions.RequestException as e:
        print(f"Fehler beim Geocoding für '{city_name}': {e}")
        return None

# (Die Funktion get_climate_data bleibt unverändert aus der letzten Antwort)
# ... [Fügen Sie die Funktion get_climate_data(city_name, latitude, longitude) hier ein] ...
def get_climate_data(city_name, latitude, longitude):
    """
    Ruft historische monatliche Durchschnittstemperaturen und gesamten Niederschlag
    für den angegebenen Ort von der Open-Meteo API ab und formatiert sie.
    (Funktion aus der vorherigen Antwort hier einfügen)
    """
    API_URL = "https://archive-api.open-meteo.com/v1/archive"
    start_date = "2023-01-01"
    end_date = "2023-12-31"

    params = {
        "latitude": latitude,
        "longitude": longitude,
        "start_date": start_date,
        "end_date": end_date,
        "daily": ["temperature_2m_mean", "precipitation_sum"],
        "timezone": "auto"
    }

    try:
        response = requests.get(API_URL, params=params)
        response.raise_for_status()
        data = response.json()
    except requests.exceptions.RequestException as e:
        print(f"Fehler bei {city_name}: {e}")
        return None

    # Datenverarbeitung (wie zuvor)
    monthly_data = defaultdict(lambda: {"temp_sum": 0.0, "precip_sum": 0.0, "count": 0})
    
    if 'daily' not in data: return None

    daily_times = data['daily']['time']
    daily_temps = data['daily']['temperature_2m_mean']
    daily_precips = data['daily']['precipitation_sum']

    for i, date_str in enumerate(daily_times):
        month = int(date_str[5:7])
        monthly_data[month]['temp_sum'] += daily_temps[i]
        monthly_data[month]['precip_sum'] += daily_precips[i]
        monthly_data[month]['count'] += 1

    temp_monthly_avg = []
    precip_monthly_sum = []
    
    for month in range(1, 13):
        if monthly_data[month]['count'] > 0:
            avg_temp = round(monthly_data[month]['temp_sum'] / monthly_data[month]['count'], 1)
            sum_precip = round(monthly_data[month]['precip_sum'], 1)
            temp_monthly_avg.append(avg_temp)
            precip_monthly_sum.append(sum_precip)
        else:
            temp_monthly_avg.append(0.0)
            precip_monthly_sum.append(0.0)

    result = {
        "name": city_name,
        "lat": latitude,
        "lng": longitude,
        "temp": temp_monthly_avg,
        "precip": precip_monthly_sum
    }

    return result

# --- HAUPTPROZESS FÜR DEN ABDAUF MIT GEOCDING ---

all_climate_data = []

for city_name in CITY_NAMES:
    
    # 2. Schritt: Koordinaten finden
    location_data = get_coordinates(city_name)
    
    if location_data:
        city = location_data['name']
        lat = location_data['lat']
        lng = location_data['lng']
        
        print(f"-> Verarbeite: {city} ({lat}, {lng})...")
        
        # 3. Schritt: Klimadaten abrufen
        data = get_climate_data(city, lat, lng)
        
        if data:
            all_climate_data.append(data)

# Speichere alle Daten in einer einzigen großen JSON-Datei
with open("geocoded_climate_data.json", "w") as f:
    json.dump(all_climate_data, f, indent=4)

print("\n--- Prozess abgeschlossen ---")
print(f"Daten für {len(all_climate_data)} Orte in 'geocoded_climate_data.json' gespeichert.")